apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-okteto-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-okteto-php
  template:
    metadata:
      labels:
        app: bot-okteto-php
    spec:
      containers:
      - image: okteto/bot-okteto-php:php
        name: bot-okteto-php
